#!/bin/sh

let a=$(cat /sys/class/backlight/intel_backlight/brightness)

if [[ $1 == "-i" ]]; then
	num=$(($a + 10))
elif [[ $1=="-d" ]]; then
	num=$(($a - 10))
else
	echo "Invalid Arg"
fi

if [[ $num -gt 208 ]]; then
	num=208
elif [[ $num -lt 20 ]]; then
	num=20
fi
echo $num
echo $num > /sys/class/backlight/intel_backlight/brightness
